# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: corlinman/v1/placeholder.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "corlinman/v1/placeholder.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1e\x63orlinman/v1/placeholder.proto\x12\x0c\x63orlinman.v1"\xa8\x01\n\x0ePlaceholderCtx\x12\x13\n\x0bsession_key\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12<\n\x08metadata\x18\x03 \x03(\x0b\x32*.corlinman.v1.PlaceholderCtx.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"_\n\rRenderRequest\x12\x10\n\x08template\x18\x01 \x01(\t\x12)\n\x03\x63tx\x18\x02 \x01(\x0b\x32\x1c.corlinman.v1.PlaceholderCtx\x12\x11\n\tmax_depth\x18\x03 \x01(\r"J\n\x0eRenderResponse\x12\x10\n\x08rendered\x18\x01 \x01(\t\x12\x17\n\x0funresolved_keys\x18\x02 \x03(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2R\n\x0bPlaceholder\x12\x43\n\x06Render\x12\x1b.corlinman.v1.RenderRequest\x1a\x1c.corlinman.v1.RenderResponseB\x02H\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "corlinman.v1.placeholder_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"H\001"
    _globals["_PLACEHOLDERCTX_METADATAENTRY"]._loaded_options = None
    _globals["_PLACEHOLDERCTX_METADATAENTRY"]._serialized_options = b"8\001"
    _globals["_PLACEHOLDERCTX"]._serialized_start = 49
    _globals["_PLACEHOLDERCTX"]._serialized_end = 217
    _globals["_PLACEHOLDERCTX_METADATAENTRY"]._serialized_start = 170
    _globals["_PLACEHOLDERCTX_METADATAENTRY"]._serialized_end = 217
    _globals["_RENDERREQUEST"]._serialized_start = 219
    _globals["_RENDERREQUEST"]._serialized_end = 314
    _globals["_RENDERRESPONSE"]._serialized_start = 316
    _globals["_RENDERRESPONSE"]._serialized_end = 390
    _globals["_PLACEHOLDER"]._serialized_start = 392
    _globals["_PLACEHOLDER"]._serialized_end = 474
# @@protoc_insertion_point(module_scope)
